import React, { useEffect, useMemo, useState } from 'react';
import { BatteryFull, BatteryLow, BatteryMedium, Check, Play, TimerReset, Zap } from 'lucide-react';
import { DailyLog, Habit, UserProfile } from '../types';
interface Props{profile:UserProfile;habits:Habit[];logs:DailyLog[];onToggleHabit:(id:string)=>void}
type Energy='low'|'normal'|'high';
type GoalGraph={title?:string;habitLinks?:Record<string,{enabled?:boolean;weight?:number;reason?:string}>};
const GOAL_KEY='habit_mosaic_v12_goal_graph',ENERGY_KEY='habit_mosaic_daily_energy_v19',TIMER_KEY='habit_mosaic_v19_mission_timer';
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const addDays=(k:string,n:number)=>{const d=new Date(`${k}T12:00:00`);d.setDate(d.getDate()+n);return dateKey(d)};
const safe=<T,>(raw:string|null,fallback:T):T=>{try{return raw?JSON.parse(raw):fallback}catch{return fallback}};
const complete=(logs:DailyLog[],id:string,k:string)=>Boolean(logs.find(l=>l.date===k)?.completedHabitIds?.includes(id));
const rate=(logs:DailyLog[],id:string,end:string)=>{let n=0;for(let i=0;i<14;i++)if(complete(logs,id,addDays(end,-i)))n++;return n/14};
const norm=(s:string)=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
const maintenance=/uong|nuoc|water|vitamin|danh rang|thuoc|skincare/i;
const timerish=/code|lap trinh|phan mem|viet|doc|hoc|ngoai ngu|hsk|jlpt|gym|tap|chay|thien|meditat/i;
export const DailyMission:React.FC<Props>=({habits,logs,onToggleHabit})=>{
 const today=dateKey(); const graph=safe<GoalGraph>(localStorage.getItem(GOAL_KEY),{}); const done=logs.find(l=>l.date===today)?.completedHabitIds||[];
 const [energy,setEnergy]=useState<Energy>(()=>safe<Record<string,Energy>>(localStorage.getItem(ENERGY_KEY),{})[today]||'normal');
 const [timer,setTimer]=useState<{id:string;at:number;minutes:number}|null>(()=>safe(localStorage.getItem(TIMER_KEY),null)); const [now,setNow]=useState(Date.now());
 useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]); useEffect(()=>{const m=safe<Record<string,Energy>>(localStorage.getItem(ENERGY_KEY),{});m[today]=energy;localStorage.setItem(ENERGY_KEY,JSON.stringify(m))},[energy,today]); useEffect(()=>{timer?localStorage.setItem(TIMER_KEY,JSON.stringify(timer)):localStorage.removeItem(TIMER_KEY)},[timer]);
 const daily=habits.filter(h=>h.frequency!=='weekly'); const linked=daily.filter(h=>graph.habitLinks?.[h.id]?.enabled!==false); const left=linked.filter(h=>!done.includes(h.id));
 const ranked=useMemo(()=>left.map(h=>{const weight=Math.max(.5,Math.min(2,Number(graph.habitLinks?.[h.id]?.weight||1)));return{h,score:weight*2+(1-rate(logs,h.id,today))}}).sort((a,b)=>b.score-a.score),[left,logs,today]);
 const next=ranked[0]?.h; const raw=norm(next?.title||''); const instant=maintenance.test(raw); const minutes=energy==='low'?2:energy==='normal'?20:45; const active=timer&&next&&timer.id===next.id?timer:null; const sec=active?Math.max(0,active.minutes*60-Math.floor((now-active.at)/1000)):0; const fmt=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
 if(!next)return <section className="rounded-[28px] border border-emerald-500/20 bg-emerald-500/5 p-6"><div className="text-[10px] uppercase tracking-widest text-emerald-400 font-black">Nhiệm vụ chính hôm nay</div><div className="mt-2 text-2xl font-black text-white">Xong phần chính rồi</div><div className="mt-1 text-sm text-slate-400">Đừng tự đẻ thêm việc chỉ để thấy mình bận.</div></section>;
 return <section className="rounded-[30px] border border-emerald-500/20 bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950/20 p-6"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.2em] text-emerald-400 font-black">Nhiệm vụ chính hôm nay</div><h2 className="mt-2 text-3xl font-black text-white">{next.title}</h2><p className="mt-2 text-xs text-slate-400">Mục tiêu dài hạn: {graph.title||'chưa đặt'}. Việc này được chọn vì còn thiếu và có trọng số cao trong Goal.</p></div><div className="grid grid-cols-3 gap-2">{([['low','Cạn pin',BatteryLow],['normal','Bình thường',BatteryMedium],['high','Sung',BatteryFull]] as any[]).map(([k,label,Icon])=><button key={k} onClick={()=>setEnergy(k)} className={`rounded-2xl border px-3 py-3 text-[10px] font-black ${energy===k?'border-emerald-400/35 bg-emerald-500/10 text-emerald-300':'border-slate-800 text-slate-600'}`}><Icon size={15} className="mx-auto mb-1"/>{label}</button>)}</div></div><div className="mt-5 rounded-3xl border border-slate-800 bg-slate-950/55 p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-[10px] uppercase text-amber-400 font-black">{instant?'LÀM THẲNG':energy==='low'?'BẢN TỐI THIỂU':'PHIÊN HÔM NAY'}</div><div className="mt-1 text-xl font-black text-white">{instant?'Làm việc này rồi đánh dấu xong':active?fmt(sec):`Làm ${minutes} phút`}</div><div className="mt-1 text-xs text-slate-500">{instant?'Không ép thói quen dạng hành động thành một bộ đếm phút.':energy==='low'?'Hai phút để phá thế đứng yên.':'Bắt đầu trước; cảm hứng đến sau cũng được.'}</div></div><div className="flex gap-2">{!instant&&<button onClick={()=>active?setTimer(null):setTimer({id:next.id,at:Date.now(),minutes})} className="rounded-2xl bg-emerald-400 px-5 py-3 text-xs font-black text-slate-950 flex items-center gap-2">{active?<TimerReset size={16}/>:<Play size={16}/>} {active?'DỪNG':'BẮT ĐẦU'}</button>}<button onClick={()=>{onToggleHabit(next.id);setTimer(null)}} className="rounded-2xl border border-emerald-500/30 bg-emerald-500/8 px-5 py-3 text-xs font-black text-emerald-200 flex items-center gap-2"><Check size={16}/> ĐÃ LÀM XONG</button></div></div></section>;
};
