import React, { useEffect, useMemo, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Activity, ArrowDown, ArrowUp, Brain, Clock3, History, MessageCircle, RotateCcw, Send, Shield, Sparkles, Swords, Target, Trophy } from 'lucide-react';
import { DailyLog, Ebook, Habit, UserProfile } from '../types';
import {
  MomentumState, RivalTrigger, RivalryMemoryItem, RivalryPsychology, defaultRivalPsychology,
  momentumLabel, momentumState, rivalPromptPayload, simulatedLegendActivity, situationalFallback,
  isWeakRivalLine, stageLabel, updateRivalPsychology,
} from '../lib/rivalryDramaV21';

interface LegendaryRivalryProps { profile:UserProfile; habits:Habit[]; logs:DailyLog[]; library:Ebook[]; onAnnounce?:(text:string)=>void; }
type Tier='practice'|'standard'|'rival'|'nemesis';
type Result='won'|'lost';
type LegendProfile={id:string;name:string;archetype:string;strength:string;philosophy:string;avatar:string;multiplier:number;specialty:'consistency'|'deep'|'curiosity'|'system'|'output'|'pattern';duelRule:string;character:string};
type MatchHistory={id:string;legendId:string;legendName:string;goal:string;startedAt:string;endedAt:string;tier:Tier;userWins:number;legendWins:number;result:Result;winType:string;biggestMargin:number};
type BattleMessage={id:string;side:'user'|'legend'|'system';text:string;at:string;reason?:string};
type BattleBeat={id:string;at:string;side:'user'|'legend'|'system';label:string;detail?:string;delta?:number};
type RivalryState={version:21;active:boolean;id?:string;legendId?:string;legendName?:string;tier:Tier;goal:string;startDate?:string;baseline:number;volatility:number;seed:number;lockedTargets:number[];history:MatchHistory[];psychology:RivalryPsychology;messages:BattleMessage[];timeline:BattleBeat[];seenCompletions:string[];lastRound:number;lastGap:number;lastNudgeDay?:string;lastStakesKey?:string;};
type GoalGraph={title?:string;habitLinks?:Record<string,{enabled?:boolean;weight?:number}>};

const KEY='habit_mosaic_legendary_rivalry_v21';
const OLD_KEY='habit_mosaic_legendary_rivalry_v12';
const GOAL_KEY='habit_mosaic_v12_goal_graph';
const LEGACY_GOAL_KEY='habit_mosaic_v11_goal';
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
const round2=(v:number)=>Math.round(v*100)/100;
const hash=(v:string)=>{let h=0;for(let i=0;i<v.length;i++)h=Math.imul(31,h)+v.charCodeAt(i)|0;return Math.abs(h)};
const dayKey=(d=new Date())=>d.toISOString().split('T')[0];
const addDays=(key:string,days:number)=>{const d=new Date(`${key}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return dayKey(d)};
const diffDays=(from:string,to:string)=>Math.floor((new Date(`${to}T12:00:00Z`).getTime()-new Date(`${from}T12:00:00Z`).getTime())/86400000);
const goalGraph=():GoalGraph=>{try{return JSON.parse(localStorage.getItem(GOAL_KEY)||'{}')}catch{return{}}};
const linkedWeight=(habitId:string)=>{const link=goalGraph().habitLinks?.[habitId];if(link?.enabled===false)return 0;return clamp(Number(link?.weight??1),.25,2)};
const completedIds=(logs:DailyLog[],date:string)=>logs.find(l=>l.date===date)?.completedHabitIds||[];
const weightedScore=(logs:DailyLog[],habits:Habit[],date:string)=>completedIds(logs,date).reduce((sum,id)=>sum+(habits.some(h=>h.id===id)?linkedWeight(id):0),0);

const LEGENDS:LegendProfile[]=[
  {id:'davinci',name:'Leonardo da Vinci',archetype:'Renaissance Mind',strength:'Tò mò · Quan sát · Sáng tạo',philosophy:'Biến tò mò thành hành động quan sát cụ thể.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=LeonardoDaVinci',multiplier:1,specialty:'curiosity',duelRule:'Mỗi ngày phải có một hành động quan sát, hỏi hoặc tạo ra thứ thật.',character:'Tò mò, tinh nghịch, hỏi ngược. Nể hành động hơn ý tưởng đẹp.'},
  {id:'curie',name:'Marie Curie',archetype:'Deep Work',strength:'Tập trung · Kiên trì',philosophy:'Lặp lại công việc khó đủ lâu để tạo tiến bộ đo được.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=MarieCurie',multiplier:1.04,specialty:'deep',duelRule:'Ưu tiên block tập trung thật; việc nhỏ không được dùng để giả cảm giác bận.',character:'Ít lời, nghiêm, hài rất khô. Công nhận công sức bằng vài chữ, không cổ vũ dài.'},
  {id:'musashi',name:'Miyamoto Musashi',archetype:'Discipline',strength:'Kỷ luật · Nhất quán',philosophy:'Thắng bằng nhịp đều, không bằng một ngày bùng nổ.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=MiyamotoMusashi',multiplier:1.08,specialty:'consistency',duelRule:'Không Zero Day; bùng nổ một ngày không bù nhiều ngày mất nhịp.',character:'Ngắn, chắc, hơi lạnh. Khích tướng bằng sự điềm tĩnh, không cần nói to.'},
  {id:'franklin',name:'Benjamin Franklin',archetype:'System Builder',strength:'Theo dõi · Phản tỉnh · Hệ thống',philosophy:'Đo được thì sửa được; sửa được thì tiến được.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=BenjaminFranklin',multiplier:.98,specialty:'system',duelRule:'Habit phải được làm và ghi lại; cuối tuần nhìn lại rồi sửa hệ thống.',character:'Dí dỏm kiểu người mê sổ sách. Thích bóc lý do nghe hợp lý nhưng không chịu nổi khi viết ra giấy.'},
  {id:'darwin',name:'Charles Darwin',archetype:'Observer',strength:'Quan sát · Ghi chép dài hạn',philosophy:'Đừng phán xét một ngày; hãy đọc mẫu hình nhiều ngày.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=CharlesDarwin',multiplier:1,specialty:'pattern',duelRule:'Thắng bằng sự đều và ghi nhận thay đổi thật.',character:'Kiên nhẫn, không phán xét một ngày xấu. Cà khịa bằng pattern chứ không bằng sĩ diện.'},
  {id:'beethoven',name:'Ludwig van Beethoven',archetype:'Creative Grit',strength:'Sáng tạo · Bền bỉ',philosophy:'Tiếp tục tạo ra thứ thật ngay cả khi điều kiện không đẹp.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=Beethoven',multiplier:1.03,specialty:'output',duelRule:'Mỗi ngày tạo output thật, kể cả nhỏ.',character:'Bộc trực, giàu cảm xúc, có chút kịch tính. Tôn trọng thứ được làm ra hơn cảm hứng.'},
  {id:'hemingway',name:'Ernest Hemingway',archetype:'Output',strength:'Viết đều · Hoàn thành',philosophy:'Đo tiến bộ bằng sản lượng thật, không bằng cảm giác bận.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=Hemingway',multiplier:1.02,specialty:'output',duelRule:'Đếm output thật. Không tính thời gian ngồi nhìn việc.',character:'Cực ngắn, thẳng, hơi cộc. Một câu đủ đau nhưng không ác.'},
  {id:'sherlock',name:'Sherlock Holmes',archetype:'Pattern Hunter',strength:'Quan sát · Suy luận · Pattern',philosophy:'Điểm yếu lặp lại là manh mối, không phải định mệnh.',avatar:'https://api.dicebear.com/7.x/personas/svg?seed=SherlockHolmes',multiplier:1.05,specialty:'pattern',duelRule:'Nemesis nhắm đúng điểm yếu lặp lại của habit.',character:'Khô, sắc, suy luận. Cà khịa bằng mâu thuẫn và pattern; không nói jargon.'},
];
const TIER_INFO:Record<Tier,{label:string;factor:number;hint:string}>={practice:{label:'Practice',factor:.84,hint:'Có lợi thế để lấy nhịp'},standard:{label:'Standard',factor:1,hint:'Cân quanh phong độ thật'},rival:{label:'Rival',factor:1.13,hint:'Ép vượt phong độ gần đây'},nemesis:{label:'Nemesis',factor:1.27,hint:'Đánh vào điểm yếu lặp lại'}};

const baselineStats=(logs:DailyLog[],habits:Habit[],start:string)=>{const values=Array.from({length:21},(_,i)=>weightedScore(logs,habits,addDays(start,-21+i)));const has=values.some(v=>v>0);const fallback=Math.max(.8,habits.reduce((s,h)=>s+linkedWeight(h.id),0)*.55);const mean=has?values.reduce((a,b)=>a+b,0)/values.length:fallback;const variance=values.reduce((s,v)=>s+Math.pow(v-mean,2),0)/Math.max(1,values.length);return{baseline:round2(Math.max(.5,mean)),volatility:round2(Math.sqrt(variance))}};
const buildTargets=(seed:number,legend:LegendProfile,tier:Tier,baseline:number,volatility:number)=>{const rel=clamp(volatility/Math.max(.5,baseline),.04,.28);const maxNoise=clamp(.06+rel*.35,.07,.17);return Array.from({length:7},(_,i)=>{const u=(hash(`${seed}-${legend.id}-${i+1}`)%10001)/10000;const noise=(u*2-1)*maxNoise;return round2(Math.max(.45,baseline*TIER_INFO[tier].factor*legend.multiplier*(1+noise)))})};
const initialState=():RivalryState=>({version:21,active:false,tier:'standard',goal:goalGraph().title||localStorage.getItem(LEGACY_GOAL_KEY)||'',baseline:1,volatility:0,seed:Date.now(),lockedTargets:[],history:[],psychology:defaultRivalPsychology(),messages:[],timeline:[],seenCompletions:[],lastRound:0,lastGap:0});
const loadState=():RivalryState=>{
  try{
    const x=JSON.parse(localStorage.getItem(KEY)||'null');
    if(x?.version===21){
      const messages=(Array.isArray(x.messages)?x.messages:[]).filter((m:any)=>m?.side!=='legend'||!isWeakRivalLine(String(m?.text||''))).slice(-36);
      return{...initialState(),...x,messages,psychology:{...defaultRivalPsychology(),...(x.psychology||{})}};
    }
  }catch{}
  try{const old=JSON.parse(localStorage.getItem(OLD_KEY)||'null');if(old)return{...initialState(),history:Array.isArray(old.history)?old.history:[],goal:old.goal||initialState().goal}}catch{}
  return initialState();
};

const latestMemory=(p:RivalryPsychology,kind?:RivalryMemoryItem['kind'])=>[...(p.memories||[])].reverse().find(m=>!kind||m.kind===kind);
const formatClock=(iso:string)=>new Date(iso).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});
const triggerReason=(t:RivalTrigger)=>({match_open:'Mở kèo',habit_done:'Bạn vừa ghi điểm',user_ahead_after_habit:'Bạn vừa vượt',legend_overtook:'Đối thủ vượt lại',user_overtook:'Bạn vượt lại',user_comeback:'Comeback',user_streak:'Chuỗi đang nóng',user_slipping:'Bạn đang tụt nhịp',late_nudge:'Cuối ngày',new_round:'Mở lượt',user_chat:'Đối đáp',match_win:'Kết trận',match_loss:'Kết trận'})[t];
const formatCountdown=(ms:number)=>{const total=Math.max(0,Math.floor(ms/1000));const h=Math.floor(total/3600);const m=Math.floor((total%3600)/60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`};

const LegendaryRivalry:React.FC<LegendaryRivalryProps>=({profile,habits,logs,library:_library,onAnnounce})=>{
  const [state,setState]=useState<RivalryState>(loadState);
  const [selectedLegendId,setSelectedLegendId]=useState(state.legendId||LEGENDS[0].id);
  const [selectedTier,setSelectedTier]=useState<Tier>(state.tier||'standard');
  const [goalInput,setGoalInput]=useState(state.goal||goalGraph().title||'');
  const [chatInput,setChatInput]=useState('');const [chatBusy,setChatBusy]=useState(false);const [flash,setFlash]=useState('');const [now,setNow]=useState(()=>Date.now());
  const processingRef=useRef(false);
  useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}},[state]);
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t)},[]);
  const today=dayKey();const legend=LEGENDS.find(l=>l.id===(state.legendId||selectedLegendId))||LEGENDS[0];
  const linkedHabits=habits.filter(h=>linkedWeight(h.id)>0);const elapsedDays=state.startDate?Math.max(0,diffDays(state.startDate,today)):0;const currentRound=clamp(elapsedDays+1,1,7);const roundIndex=elapsedDays+1;const calendarFinished=state.active&&elapsedDays>=7;
  const attackHabit=(round:number)=>linkedHabits.length?linkedHabits[hash(`${state.seed}-attack-${round}-${legend.specialty}`)%linkedHabits.length]:null;
  const playerScore=(round:number)=>{if(!state.startDate)return 0;const date=addDays(state.startDate,round-1);const base=weightedScore(logs,habits,date);const ids=completedIds(logs,date);const attack=attackHabit(round);const attackBonus=attack&&ids.includes(attack.id)?Math.min(.45,linkedWeight(attack.id)*.25):0;const prev=round>1?weightedScore(logs,habits,addDays(date,-1))>0:false;const recovery=round>1&&!prev&&base>0?.12:0;const consistency=round>2&&weightedScore(logs,habits,addDays(date,-1))>0&&weightedScore(logs,habits,addDays(date,-2))>0?.12:0;return round2(base+attackBonus+recovery+consistency)};
  const historicalResults=useMemo(()=>{if(!state.startDate)return[] as Array<{round:number;user:number;legend:number;winner:'user'|'legend';margin:number}>;const count=Math.min(7,Math.max(0,elapsedDays));return Array.from({length:count},(_,i)=>{const r=i+1;const u=playerScore(r);const o=state.lockedTargets[i]??state.baseline;return{round:r,user:u,legend:o,winner:u>=o?'user':'legend',margin:round2(u-o)}})},[state.startDate,state.lockedTargets,elapsedDays,logs,habits]);
  const currentUser=playerScore(currentRound),currentLegend=state.lockedTargets[currentRound-1]??state.baseline;const gap=round2(currentUser-currentLegend);const previousGap=state.lastGap||0;
  const currentRoundLockedWin=state.active&&!calendarFinished&&currentRound<=7&&currentUser>=currentLegend;
  const currentResult=currentRoundLockedWin?{round:currentRound,user:currentUser,legend:currentLegend,winner:'user' as const,margin:gap}:null;
  const results=currentResult?[...historicalResults,currentResult]:historicalResults;
  const userWins=results.filter(r=>r.winner==='user').length,legendWins=results.filter(r=>r.winner==='legend').length;
  const final=state.active&&(userWins>=4||legendWins>=4||calendarFinished);
  const incomplete=linkedHabits.filter(h=>!completedIds(logs,today).includes(h.id)).map(h=>({h,w:linkedWeight(h.id)})).sort((a,b)=>b.w-a.w);const nextMove=incomplete[0];const projected=round2(currentUser+(nextMove?.w||0)-currentLegend);const remaining=Math.max(0,round2(currentLegend-currentUser));
  const momentum:MomentumState=momentumState({gap,previousGap,seriesUser:userWins,seriesLegend:legendWins,round:currentRound,projectedGap:projected});const activity=simulatedLegendActivity(legend.id,currentRound,currentLegend);
  const seriesBehind=userWins<legendWins;const comebackPossible=seriesBehind&&Boolean(nextMove)&&projected>=0;
  const matchPointUser=userWins===3&&legendWins<3;const matchPointLegend=legendWins===3&&userWins<3;const finalRound=userWins===3&&legendWins===3;
  const roundWinSeries=`${userWins+1}-${legendWins}`;const roundLoseSeries=`${userWins}-${legendWins+1}`;
  const roundStakes=finalRound?'LƯỢT 7 · THẮNG LƯỢT NÀY = LẤY CẢ SERIES':matchPointUser?`MATCH POINT · THẮNG HÔM NAY = CHỐT SERIES ${roundWinSeries}`:matchPointLegend?`ELIMINATION POINT · THUA HÔM NAY = MẤT SERIES ${roundLoseSeries}`:`THẮNG LƯỢT → ${roundWinSeries} · THUA LƯỢT → ${roundLoseSeries}`;
  const stakesKey=(state.active&&!final&&(matchPointUser||matchPointLegend||finalRound))?`${state.id}|${today}|R${currentRound}|${userWins}-${legendWins}|${gap>=0?'ahead':'behind'}`:'';
  const dayEnd=(()=>{const d=new Date(now);d.setHours(23,59,59,999);return d.getTime()})();const timeLeft=formatCountdown(dayEnd-now);
  const progressPct=clamp(currentUser/Math.max(currentLegend,.01)*100,0,125);
  const pressurePct=clamp(100-progressPct,0,100);
  const counterPlan=(()=>{let acc=0;const plan:typeof incomplete=[];for(const item of incomplete){plan.push(item);acc+=item.w;if(currentUser+acc>=currentLegend)break}return{items:plan,gain:round2(acc),projected:round2(currentUser+acc-currentLegend),possible:currentUser+acc>=currentLegend}})();
  const signatureHabit=attackHabit(currentRound);const signatureDone=Boolean(signatureHabit&&completedIds(logs,today).includes(signatureHabit.id));const signatureBonus=signatureHabit?Math.min(.45,linkedWeight(signatureHabit.id)*.25):0;

  const fallbackFor=(trigger:RivalTrigger,habit='')=>situationalFallback(legend,trigger,{gap,habit,stage:state.psychology.stage,memory:latestMemory(state.psychology,'promise'),seed:`${state.id}|${trigger}|${state.messages.length}`,seriesUser:userWins,seriesLegend:legendWins,round:currentRound,userScore:currentUser,legendScore:currentLegend,remaining,nextHabit:nextMove?.h.title});
  const requestReply=async(trigger:RivalTrigger,userText='',habit='')=>{const fallback=fallbackFor(trigger,habit);const bridge=(window as any).habitMosaicDesktop;if(!bridge?.requestApi)return fallback;try{const extra=rivalPromptPayload({psychology:state.psychology,momentum,gap,previousGap,projectedGap:projected,remaining,memory:latestMemory(state.psychology,'promise'),seriesUser:userWins,seriesLegend:legendWins,round:currentRound,nextHabit:nextMove?.h.title});const result=await bridge.requestApi('/api/generate-rival-turn',{legendName:legend.name,archetype:legend.archetype,philosophy:legend.philosophy,strength:legend.strength,duelRule:legend.duelRule,characterCard:legend.character,userText,trigger,habit,goal:state.goal,userScore:currentUser,legendScore:currentLegend,round:currentRound,series:`${userWins}-${legendWins}`,roundStakes,recentMessages:state.messages.slice(-10).map(m=>`${m.side}:${m.text}`).join(' | '),seriousness:/nản|bỏ cuộc|mệt|kiệt|tệ/.test(userText.toLocaleLowerCase('vi-VN'))?'high':'normal',emotionalBeat:state.psychology.lastBeat,...extra});const text=String(result?.body?.reply||'').trim();return isWeakRivalLine(text)?fallback:(text||fallback)}catch{return fallback}};

  useEffect(()=>{if(!state.active||final||!state.id||processingRef.current)return;processingRef.current=true;let cancelled=false;(async()=>{try{const done=completedIds(logs,today);const seen=new Set(state.seenCompletions);const fresh=done.filter(id=>!seen.has(id));let nextPsych=state.psychology;const newMessages:BattleMessage[]=[];const newBeats:BattleBeat[]=[];for(const id of fresh){const h=habits.find(x=>x.id===id);if(!h)continue;const after=round2(playerScore(currentRound)-currentLegend);const trigger:RivalTrigger=previousGap<=0&&after>0?'user_overtook':after>.35?'user_ahead_after_habit':(seriesBehind&&after>previousGap+.25?'user_comeback':'habit_done');const at=new Date().toISOString();nextPsych=updateRivalPsychology(nextPsych,trigger,{gap:after,seriesUser:userWins,seriesLegend:legendWins,habit:h.title,at});const text=await requestReply(trigger,'',h.title);newMessages.push({id:`auto-${Date.now()}-${id}`,side:'legend' as const,text,at,reason:triggerReason(trigger)});newBeats.push({id:`beat-u-${Date.now()}-${id}`,at,side:'user',label:`Hoàn thành ${h.title}`,delta:linkedWeight(id)});newBeats.push({id:`beat-l-${Date.now()}-${id}`,at,side:'legend',label:'Đối thủ phản ứng',detail:text.slice(0,100)});if(previousGap<=0&&after>0)setFlash('POSITION CHANGED');else if(seriesBehind&&after>previousGap+.25)setFlash('COMEBACK');}
    const hour=new Date().getHours();const lateKey=`${today}:${state.id}`;if(hour>=21&&incomplete.length&&state.lastNudgeDay!==lateKey){const at=new Date().toISOString();nextPsych=updateRivalPsychology(nextPsych,'late_nudge',{gap,seriesUser:userWins,seriesLegend:legendWins,habit:nextMove?.h.title,at});const text=await requestReply('late_nudge','',nextMove?.h.title||'việc còn lại');newMessages.push({id:`late-${Date.now()}`,side:'legend',text,at,reason:'Cuối ngày'});newBeats.push({id:`beat-late-${Date.now()}`,at,side:'legend',label:'Áp lực cuối ngày',detail:text.slice(0,100)});}
    if(state.lastRound>0&&state.lastRound!==currentRound){const at=new Date().toISOString();const text=await requestReply('new_round');newMessages.push({id:`round-${Date.now()}`,side:'legend',text,at,reason:'Mở lượt mới'});newBeats.push({id:`beat-round-${Date.now()}`,at,side:'system',label:`Round ${currentRound} bắt đầu`});}
    if(!cancelled&&(fresh.length||newMessages.length||state.lastRound!==currentRound)){setState(p=>({...p,psychology:nextPsych,messages:[...p.messages,...newMessages].slice(-36),timeline:[...p.timeline,...newBeats].slice(-60),seenCompletions:Array.from(new Set([...p.seenCompletions,...done])),lastRound:currentRound,lastGap:gap,lastNudgeDay:hour>=21&&incomplete.length?lateKey:p.lastNudgeDay}));}}
    finally{processingRef.current=false}})();return()=>{cancelled=true;processingRef.current=false};
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[state.active,state.id,today,logs,currentRound,currentUser,currentLegend,final]);

  useEffect(()=>{
    if(!stakesKey||state.lastStakesKey===stakesKey||processingRef.current)return;
    let cancelled=false;
    (async()=>{
      const trigger:RivalTrigger=gap<0?'user_slipping':'habit_done';
      const at=new Date().toISOString();
      const psychology=updateRivalPsychology(state.psychology,trigger,{gap,seriesUser:userWins,seriesLegend:legendWins,habit:nextMove?.h.title,at});
      const text=await requestReply(trigger,'',nextMove?.h.title||'');
      if(cancelled)return;
      setState(p=>p.lastStakesKey===stakesKey?p:{...p,lastStakesKey:stakesKey,psychology,messages:[...p.messages,{id:`stakes-${Date.now()}`,side:'legend',text,at,reason:finalRound?'Final round':matchPointUser?'Match point':'Elimination point'}].slice(-36),timeline:[...p.timeline,{id:`stakes-beat-${Date.now()}`,at,side:'system',label:finalRound?'FINAL ROUND':matchPointUser?'MATCH POINT':'ELIMINATION POINT',detail:roundStakes}].slice(-60)});
    })();
    return()=>{cancelled=true};
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[stakesKey]);

  useEffect(()=>{if(!flash)return;const t=setTimeout(()=>setFlash(''),2200);return()=>clearTimeout(t)},[flash]);
  useEffect(()=>{if(!final||!state.id)return;const already=state.history.some(h=>h.id===state.id);if(already)return;const result:Result=userWins>legendWins?'won':'lost';const wasBehind=results.slice(0,-1).some((_,i)=>results.slice(0,i+1).filter(r=>r.winner==='user').length<results.slice(0,i+1).filter(r=>r.winner==='legend').length);const total=results.reduce((s,r)=>s+r.margin,0);const winType=result==='won'?(userWins===4&&legendWins===0?'PERFECT WIN':wasBehind?'COMEBACK WIN':Math.abs(total)<.6?'NARROW WIN':userWins===4?'SERIES WIN':'WIN'):'DEFEAT · DATA ACQUIRED';const at=new Date().toISOString();const psychology=updateRivalPsychology(state.psychology,result==='won'?'match_win':'match_loss',{gap,seriesUser:userWins,seriesLegend:legendWins,at});const item:MatchHistory={id:state.id,legendId:legend.id,legendName:legend.name,goal:state.goal,startedAt:state.startDate||today,endedAt:today,tier:state.tier,userWins,legendWins,result,winType,biggestMargin:Math.max(0,...results.map(r=>Math.abs(r.margin)))};setState(p=>({...p,psychology,history:[item,...p.history].slice(0,60)}));onAnnounce?.(result==='won'?`${winType}: Tôi thắng ${legend.name} ${userWins}-${legendWins}.`:`Tôi thua ${legend.name} ${userWins}-${legendWins}. Trận kết thúc, hành trình thì chưa.`);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[final,state.id]);

  const start=()=>{if(!linkedHabits.length)return;const selected=LEGENDS.find(l=>l.id===selectedLegendId)||LEGENDS[0];const goal=goalInput.trim()||goalGraph().title||'Duy trì hệ thống thói quen hiện tại';const stats=baselineStats(logs,habits,today);const id=`lr21-${Date.now()}-${selected.id}`;const seed=hash(id);const targets=buildTargets(seed,selected,selectedTier,stats.baseline,stats.volatility);const at=new Date().toISOString();const psych=defaultRivalPsychology();const opening=situationalFallback(selected,'match_open',{gap:0,stage:psych.stage,seed:id});setState(p=>({...initialState(),active:true,id,legendId:selected.id,legendName:selected.name,tier:selectedTier,goal,startDate:today,baseline:stats.baseline,volatility:stats.volatility,seed,lockedTargets:targets,history:p.history,psychology:psych,messages:[{id:`open-${Date.now()}`,side:'legend',text:opening,at,reason:'Mở kèo'}],timeline:[{id:`start-${Date.now()}`,at,side:'system',label:'Kèo đã khóa',detail:'7 target được khóa ngay từ đầu'}],seenCompletions:completedIds(logs,today),lastRound:1,lastGap:0}));};
  const cancel=()=>setState(p=>({...p,active:false}));
  const sendChat=async()=>{const text=chatInput.trim();if(!text||chatBusy||!state.id)return;const at=new Date().toISOString();const psych=updateRivalPsychology(state.psychology,'user_chat',{gap,seriesUser:userWins,seriesLegend:legendWins,userText:text,at});setChatInput('');setChatBusy(true);setState(p=>({...p,psychology:psych,messages:[...p.messages,{id:`u-${Date.now()}`,side:'user' as const,text,at,reason:'Đối đáp'}].slice(-36),timeline:[...p.timeline,{id:`ub-${Date.now()}`,at,side:'user' as const,label:'Bạn lên tiếng',detail:text.slice(0,100)}].slice(-60)}));const reply=await requestReply('user_chat',text,nextMove?.h.title||'');setState(p=>({...p,messages:[...p.messages,{id:`l-${Date.now()}`,side:'legend' as const,text:reply,at:new Date().toISOString(),reason:'Đối đáp'}].slice(-36)}));setChatBusy(false)};

  const last=state.history[0];const wins=(id:string)=>state.history.filter(h=>h.legendId===id&&h.result==='won').length;const losses=(id:string)=>state.history.filter(h=>h.legendId===id&&h.result==='lost').length;
  const latestLegendRaw=[...state.messages].reverse().find(m=>m.side==='legend')?.text||'';
  const liveRivalLine=isWeakRivalLine(latestLegendRaw)?fallbackFor(gap<0?'user_slipping':'habit_done',nextMove?.h.title||''):latestLegendRaw;
  const roundState=gap>=0?'BẠN ĐÃ KHÓA LỢI THẾ':remaining<=.5?'CHỈ CÒN MỘT NHỊP':'ĐỐI THỦ ĐANG GIỮ LƯỢT';
  const seriesHeadline=finalRound?'FINAL ROUND':matchPointUser?'MATCH POINT':matchPointLegend?'ELIMINATION POINT':userWins===legendWins?'SERIES CÂN BẰNG':userWins>legendWins?'BẠN ĐANG DẪN SERIES':'ĐỐI THỦ ĐANG DẪN SERIES';
  const completedToday=completedIds(logs,today).length;

  if(!state.active)return <div className="rounded-[2rem] border border-rose-500/25 bg-gradient-to-br from-slate-950 via-slate-900 to-rose-950/30 p-6 shadow-2xl">
    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-5 mb-6"><div><div className="flex items-center gap-2 text-rose-400"><Swords size={20}/><span className="text-[10px] font-black uppercase tracking-[.28em]">Rivalry Arena V22 · Competition First</span></div><h3 className="text-3xl font-black text-white mt-2">Chọn một đối thủ. Khóa kèo. Lấy 4 lượt trước.</h3><p className="text-sm text-slate-400 mt-2 max-w-3xl">Mỗi ngày là một round. Điểm habit thật quyết định round; series dừng ngay khi một bên đạt 4. Đối thủ nhớ lần bị vượt, comeback và lời bạn từng gáy.</p></div><div className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-800 text-[10px] text-slate-400 font-bold flex items-center gap-2"><Shield size={14}/> Benchmark mô phỏng theo nhân vật, không phải người thật</div></div>
    {last?.result==='lost'&&<div className="mb-5 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 flex items-center justify-between"><div><div className="text-[10px] uppercase font-black text-amber-400">REMATCH AVAILABLE</div><div className="text-sm font-bold text-white">Phục thù {last.legendName} · trận trước {last.userWins}-{last.legendWins}</div></div><RotateCcw className="text-amber-400"/></div>}
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3 mb-6">{LEGENDS.map(item=>{const sel=selectedLegendId===item.id;return <button key={item.id} onClick={()=>setSelectedLegendId(item.id)} className={`text-left p-4 rounded-2xl border transition-all ${sel?'border-rose-500 bg-rose-500/12 shadow-lg shadow-rose-950/30 -translate-y-0.5':'border-slate-800 bg-slate-950/35 hover:border-slate-700 hover:-translate-y-0.5'}`}><div className="flex items-center gap-3"><img src={item.avatar} className="w-12 h-12 rounded-xl bg-slate-800"/><div><div className="text-xs font-black text-white">{item.name}</div><div className="text-[9px] uppercase text-slate-500 font-bold">{item.archetype}</div></div></div><div className="text-[10px] text-slate-400 mt-3">{item.strength}</div><div className="text-[11px] text-slate-500 mt-2 line-clamp-2">{item.character}</div><div className="flex gap-3 mt-3 text-[9px]"><span className="text-emerald-400">W {wins(item.id)}</span><span className="text-rose-400">L {losses(item.id)}</span></div></button>})}</div>
    <div className="grid md:grid-cols-3 gap-3"><input value={goalInput} onChange={e=>setGoalInput(e.target.value)} placeholder="Mục tiêu đang đấu..." className="md:col-span-2 px-4 py-3 rounded-2xl bg-slate-950/60 border border-slate-800 text-sm text-white outline-none focus:border-rose-500"/><select value={selectedTier} onChange={e=>setSelectedTier(e.target.value as Tier)} className="px-4 py-3 rounded-2xl bg-slate-950 border border-slate-800 text-sm text-white">{Object.entries(TIER_INFO).map(([id,x])=><option key={id} value={id}>{x.label} · {x.hint}</option>)}</select></div>
    <button onClick={start} disabled={!linkedHabits.length} className="mt-4 w-full py-4 rounded-2xl bg-gradient-to-r from-rose-600 via-fuchsia-600 to-amber-500 text-white font-black text-sm disabled:opacity-40 flex items-center justify-center gap-2 shadow-lg shadow-rose-950/30"><Swords size={18}/> KHÓA KÈO · FIRST TO 4</button>
  </div>;

  return <div className="rounded-[2rem] border border-rose-500/30 bg-slate-950 overflow-hidden shadow-2xl relative">
    <AnimatePresence>{flash&&<motion.div initial={{opacity:0,scale:.86,y:-10}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:1.08}} className="absolute z-40 inset-x-0 top-24 flex justify-center pointer-events-none"><div className="px-7 py-3 rounded-2xl bg-amber-300 text-slate-950 font-black tracking-[.2em] shadow-2xl border border-white/50">{flash}</div></motion.div>}</AnimatePresence>

    <div className={`px-5 md:px-7 py-3 border-b ${matchPointUser||matchPointLegend||finalRound?'border-amber-400/35 bg-amber-400/10':'border-rose-500/20 bg-rose-950/20'}`}>
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-2"><div className="flex items-center gap-2"><Swords size={15} className={matchPointUser||matchPointLegend||finalRound?'text-amber-300':'text-rose-400'}/><span className={`text-[10px] font-black uppercase tracking-[.22em] ${matchPointUser||matchPointLegend||finalRound?'text-amber-300':'text-rose-300'}`}>{roundStakes}</span><span className="rounded-md border border-white/10 bg-white/[.04] px-1.5 py-0.5 text-[8px] font-black tracking-[.14em] text-slate-500">V23 ARENA</span></div><div className="flex items-center gap-3 text-[10px] font-bold"><span className="text-slate-500">ROUND {currentRound}/7</span><span className="text-slate-700">•</span><span className="text-slate-400">khóa sau {timeLeft}</span><button onClick={cancel} className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-slate-500 hover:text-white">Hủy kèo</button></div></div>
    </div>

    {(matchPointUser||matchPointLegend||finalRound)&&<div className="mx-5 md:mx-7 mt-5 rounded-3xl border border-amber-300/45 bg-gradient-to-r from-amber-400/15 via-rose-500/10 to-slate-950 p-5 md:p-6 shadow-[0_0_50px_rgba(251,191,36,.08)]">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div><div className="text-[10px] uppercase tracking-[.32em] text-amber-300 font-black">{seriesHeadline}</div><div className="text-2xl md:text-3xl font-black text-white mt-1">{finalRound?'Không còn lượt sau.':matchPointUser?`LẤY ROUND ${currentRound} = KẾT THÚC ${roundWinSeries}`:`MẤT ROUND ${currentRound} = SERIES KẾT THÚC ${roundLoseSeries}`}</div><div className="text-xs text-slate-400 mt-2">{gap<0?`${legend.name} đang giữ round. Bạn còn thiếu ${remaining.toFixed(2)} điểm.`:`Bạn đang giữ round với +${gap.toFixed(2)}. Đừng trao nó lại.`}</div></div>
        <div className="shrink-0 text-center px-5 py-3 rounded-2xl border border-amber-300/25 bg-slate-950/55"><div className="text-[9px] text-slate-500 font-black">SERIES</div><div className="text-3xl font-black"><span className="text-cyan-300">{userWins}</span><span className="text-slate-700 mx-2">—</span><span className="text-rose-300">{legendWins}</span></div></div>
      </div>
    </div>}

    <div className="p-5 md:p-7 bg-gradient-to-b from-slate-950 via-slate-950 to-rose-950/15">
      <div className="grid lg:grid-cols-[1fr_1.05fr_1fr] gap-4 items-stretch">
        <div className={`rounded-3xl border p-5 relative overflow-hidden ${gap>=0?'border-cyan-400/35 bg-cyan-500/8':'border-cyan-500/15 bg-slate-900/60'}`}>
          <div className="absolute -top-16 -left-16 w-40 h-40 rounded-full bg-cyan-500/10 blur-3xl"/>
          <div className="relative flex items-center gap-3"><div className="w-14 h-14 rounded-2xl border border-cyan-400/30 bg-cyan-400/10 flex items-center justify-center text-xl font-black text-cyan-200">{(profile.displayName||'YOU').slice(0,1).toUpperCase()}</div><div><div className="text-[9px] uppercase tracking-[.24em] text-cyan-400 font-black">YOU</div><div className="text-lg font-black text-white truncate">{profile.displayName||'Bạn'}</div><div className="text-[10px] text-slate-500">{completedToday} habit hoàn thành hôm nay</div></div></div>
          <div className="relative mt-5"><div className="text-[10px] uppercase text-slate-500 font-black">Điểm round</div><div className="text-5xl font-black text-white mt-1">{currentUser.toFixed(2)}</div><div className={`text-xs font-black mt-2 ${gap>=0?'text-emerald-400':'text-rose-300'}`}>{gap>=0?`ĐANG DẪN +${gap.toFixed(2)}`:`CÒN THIẾU ${remaining.toFixed(2)}`}</div></div>
        </div>

        <div className="rounded-3xl border border-white/10 bg-gradient-to-b from-slate-900/90 to-slate-950 p-5 flex flex-col justify-between text-center relative overflow-hidden">
          <div className="absolute inset-x-12 top-1/2 h-px bg-gradient-to-r from-transparent via-rose-400/50 to-transparent"/>
          <div className="relative"><div className={`text-[10px] uppercase tracking-[.28em] font-black ${matchPointUser||matchPointLegend||finalRound?'text-amber-300':'text-slate-500'}`}>{seriesHeadline}</div><div className="flex items-end justify-center gap-4 mt-2"><div><div className="text-5xl font-black text-cyan-300">{userWins}</div><div className="text-[9px] text-slate-600 font-black">ROUNDS</div></div><div className="pb-4 text-2xl font-black text-slate-700">VS</div><div><div className="text-5xl font-black text-rose-300">{legendWins}</div><div className="text-[9px] text-slate-600 font-black">ROUNDS</div></div></div></div>
          <div className="relative mt-5 grid grid-cols-7 gap-1.5">{Array.from({length:7},(_,i)=>{const r=i+1;const rr=results.find(x=>x.round===r);const isCurrent=r===currentRound&&!final;return <div key={r} className={`h-9 rounded-xl border flex items-center justify-center text-[9px] font-black ${rr?.winner==='user'?'border-cyan-400/40 bg-cyan-400/15 text-cyan-200':rr?.winner==='legend'?'border-rose-400/40 bg-rose-400/15 text-rose-200':isCurrent?'border-amber-300/50 bg-amber-300/10 text-amber-200 animate-pulse':'border-slate-800 bg-slate-900 text-slate-700'}`}>{rr?(rr.winner==='user'?'W':'L'):isCurrent?'LIVE':r}</div>})}</div>
          <div className="relative mt-4 text-[10px] text-slate-500">FIRST TO 4 · {stageLabel(state.psychology.stage)}</div>
        </div>

        <div className={`rounded-3xl border p-5 relative overflow-hidden ${gap<0?'border-rose-400/40 bg-rose-500/10':'border-rose-500/15 bg-slate-900/60'}`}>
          <div className="absolute -top-16 -right-16 w-40 h-40 rounded-full bg-rose-500/15 blur-3xl"/>
          <div className="relative flex items-center justify-end gap-3 text-right"><div><div className="text-[9px] uppercase tracking-[.24em] text-rose-400 font-black">RIVAL</div><div className="text-lg font-black text-white">{legend.name}</div><div className="text-[10px] text-slate-500">{legend.archetype}</div></div><img src={legend.avatar} className="w-14 h-14 rounded-2xl bg-slate-800 border border-rose-400/30"/></div>
          <div className="relative mt-5 text-right"><div className="text-[10px] uppercase text-slate-500 font-black">Mốc phải hạ</div><div className="text-5xl font-black text-rose-200 mt-1">{currentLegend.toFixed(2)}</div><div className="text-xs font-black text-rose-300 mt-2">{activity.offDay?'PHONG ĐỘ HÔM NAY THẤP':'ĐANG GIỮ NHỊP'}</div><div className="mt-3 inline-flex items-center gap-2 rounded-xl border border-rose-400/15 bg-slate-950/55 px-3 py-2 text-[9px] text-slate-400"><Activity size={12} className="text-rose-300"/> Nhịp mô phỏng: {activity.state} · {Math.round(activity.progress*100)}% ngày</div></div>
        </div>
      </div>

      <div className={`mt-4 rounded-3xl border p-5 ${gap>=0?'border-emerald-400/30 bg-emerald-400/8':'border-rose-400/30 bg-rose-400/8'}`}>
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div className={`text-[10px] uppercase tracking-[.25em] font-black ${gap>=0?'text-emerald-300':'text-rose-300'}`}>{roundState} · {momentumLabel(momentum)}</div><div className="text-2xl md:text-3xl font-black text-white mt-1">{gap>=0?`Lượt ${currentRound} đang nằm trong tay bạn.`:`${legend.name} đang hơn ${Math.abs(gap).toFixed(2)} điểm.`}</div><div className="text-xs text-slate-400 mt-2">{gap>=0?'Điểm đã vượt mốc khóa. Đối thủ không thể tự nâng target để đuổi theo.':`Áp lực hiện tại ${Math.round(pressurePct)}% · còn ${timeLeft} trước khi round khóa.`}</div></div><div className="text-right"><div className="text-[9px] uppercase text-slate-500 font-black">GAP</div><div className={`text-3xl font-black ${gap>=0?'text-emerald-300':'text-rose-300'}`}>{gap>=0?'+':''}{gap.toFixed(2)}</div></div></div>
        <div className="mt-4 h-4 bg-slate-900 rounded-full overflow-hidden border border-slate-800 relative"><motion.div animate={{width:`${Math.min(100,progressPct)}%`}} transition={{type:'spring',stiffness:120,damping:18}} className={`h-full ${gap>=0?'bg-gradient-to-r from-cyan-400 to-emerald-400':'bg-gradient-to-r from-cyan-500 to-amber-300'}`}/><div className="absolute right-0 inset-y-0 w-0.5 bg-rose-300 shadow-[0_0_12px_rgba(253,164,175,.9)]"/></div>
        <div className="flex justify-between mt-2 text-[9px] font-bold"><span className="text-cyan-400">YOU {currentUser.toFixed(2)}</span><span className="text-rose-300">TARGET {currentLegend.toFixed(2)}</span></div>
      </div>

      <div className="mt-4 rounded-3xl border border-rose-400/25 bg-gradient-to-r from-rose-950/55 via-slate-900 to-slate-950 p-5 md:p-6 relative overflow-hidden">
        <div className="absolute right-0 top-0 text-[7rem] leading-none font-black text-rose-500/[.04] select-none">“</div>
        <div className="relative flex items-start gap-4"><img src={legend.avatar} className="w-12 h-12 rounded-2xl bg-slate-800 border border-rose-400/30 shrink-0"/><div className="min-w-0"><div className="text-[9px] uppercase tracking-[.24em] text-rose-400 font-black">ĐỐI THỦ NÓI THẲNG</div><div className="text-lg md:text-xl font-black text-white mt-2 leading-relaxed">“{liveRivalLine}”</div><div className="text-[10px] text-slate-500 mt-2">{legend.name} · {stageLabel(state.psychology.stage)} · heat {Math.round(state.psychology.competitiveHeat*100)}%</div></div></div>
      </div>

      <div className="mt-4 grid lg:grid-cols-12 gap-4">
        <div className="lg:col-span-7 rounded-3xl border border-amber-400/30 bg-amber-400/8 p-5">
          <div className="flex items-center gap-2 text-[10px] uppercase tracking-[.23em] text-amber-300 font-black"><Target size={14}/> PHẢN CÔNG NGAY</div>
          {gap>=0?<div className="mt-3"><div className="text-2xl font-black text-white">Không cần thêm điểm để lấy round.</div><div className="text-xs text-slate-400 mt-2">Bạn đã vượt target. Phần còn lại hôm nay chỉ giúp củng cố habit thật, không làm đối thủ tự tăng mốc.</div></div>:counterPlan.items.length?<><div className="mt-3 text-xl font-black text-white">{counterPlan.possible?'Chuỗi đòn đủ để lật lượt:':'Hôm nay chưa có đủ điểm khả dụng để chạm target.'}</div><div className="mt-3 flex flex-wrap gap-2">{counterPlan.items.map((x,i)=><div key={x.h.id} className="px-3 py-2 rounded-xl border border-amber-300/20 bg-slate-950/50 text-xs text-white"><span className="text-amber-300 font-black">{i+1}</span> · {x.h.title} <b className="text-emerald-300">+{x.w.toFixed(2)}</b></div>)}</div><div className="mt-3 text-xs text-slate-400">Tổng +{counterPlan.gain.toFixed(2)} → gap dự kiến <b className={counterPlan.projected>=0?'text-emerald-300':'text-rose-300'}>{counterPlan.projected>=0?'+':''}{counterPlan.projected.toFixed(2)}</b></div></>:<div className="mt-3 text-sm text-slate-500">Không còn habit nào chưa hoàn thành hôm nay.</div>}
        </div>
        <div className="lg:col-span-5 rounded-3xl border border-violet-400/25 bg-violet-400/7 p-5"><div className="text-[10px] uppercase tracking-[.23em] text-violet-300 font-black">ĐÒN ĐẶC TRƯNG · {legend.archetype}</div>{signatureHabit?<><div className="text-lg font-black text-white mt-3">{signatureHabit.title}</div><div className="text-xs text-slate-400 mt-2">Hoàn thành habit này trong round sẽ kích hoạt bonus hệ thống <b className="text-violet-300">+{signatureBonus.toFixed(2)}</b>.</div><div className={`mt-3 inline-flex px-2.5 py-1 rounded-lg text-[9px] font-black border ${signatureDone?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':'border-violet-400/20 bg-violet-400/10 text-violet-300'}`}>{signatureDone?'ĐÃ COUNTER':'CHƯA COUNTER'}</div></>:<div className="text-xs text-slate-500 mt-3">Chưa có habit liên kết.</div>}</div>
      </div>

      <div className="mt-4 grid xl:grid-cols-12 gap-4">
        <div className="xl:col-span-7 rounded-3xl border border-slate-800 bg-slate-900/45 overflow-hidden">
          <div className="p-4 border-b border-slate-800 flex items-center justify-between"><div><div className="text-[9px] uppercase tracking-[.22em] text-slate-400 font-black">BATTLE LOG</div><div className="text-xs text-slate-600 mt-1">Điểm chỉ đến từ habit thật. Mỗi lần vượt/tuột vị trí đều trở thành một nhịp của cuộc đấu.</div></div><Clock3 size={15} className="text-slate-600"/></div>
          <div className="p-4 grid md:grid-cols-2 gap-3 max-h-72 overflow-auto">{state.timeline.slice(-10).reverse().map(b=><div key={b.id} className={`rounded-2xl border p-3 ${b.side==='user'?'border-cyan-500/15 bg-cyan-500/5':b.side==='legend'?'border-rose-500/15 bg-rose-500/5':'border-slate-800 bg-slate-950/40'}`}><div className="flex items-start justify-between gap-3"><div className="text-xs font-bold text-white">{b.label}</div><div className="text-[9px] text-slate-600 shrink-0">{formatClock(b.at)}</div></div>{b.detail&&<div className="text-[10px] text-slate-500 mt-1 line-clamp-2">{b.detail}</div>}{typeof b.delta==='number'&&<div className="text-[10px] text-emerald-400 font-black mt-2">+{b.delta.toFixed(2)}</div>}</div>)}{!state.timeline.length&&<div className="text-xs text-slate-600">Chưa có đòn nào. Làm habit đầu tiên để mở battle log.</div>}</div>
        </div>
        <div className="xl:col-span-5 rounded-3xl border border-rose-500/20 bg-slate-900/45 overflow-hidden">
          <div className="p-4 border-b border-slate-800"><div className="flex items-center gap-2"><MessageCircle size={14} className="text-rose-400"/><div className="text-[9px] uppercase tracking-[.22em] text-rose-400 font-black">ĐỐI ĐÁP</div></div><div className="text-[10px] text-slate-600 mt-1">Gáy được. Nhưng câu nói không cộng điểm.</div></div>
          <div className="p-4 space-y-2 max-h-52 overflow-auto">{state.messages.slice(-6).map(m=><div key={m.id} className={`flex ${m.side==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[90%] rounded-2xl px-3 py-2 ${m.side==='user'?'bg-cyan-500/10 border border-cyan-500/15':'bg-rose-500/10 border border-rose-500/15'}`}><div className="text-xs text-white whitespace-pre-wrap">{m.text}</div><div className="text-[8px] text-slate-600 mt-1">{m.reason||''} · {formatClock(m.at)}</div></div></div>)}</div>
          <div className="p-3 border-t border-slate-800 flex gap-2"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder={`Nói với ${legend.name}...`} className="flex-1 min-w-0 px-3 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white outline-none focus:border-rose-500"/><button onClick={sendChat} disabled={chatBusy||!chatInput.trim()} className="w-10 h-10 rounded-xl bg-rose-600 text-white flex items-center justify-center disabled:opacity-40">{chatBusy?<Sparkles size={15} className="animate-pulse"/>:<Send size={15}/>}</button></div>
        </div>
      </div>

      <details className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/55 group"><summary className="cursor-pointer list-none p-4 flex items-center justify-between text-[10px] font-black uppercase tracking-[.18em] text-slate-500"><span>Luật công bằng · ký ức · trạng thái đối thủ</span><span className="text-slate-700">MỞ</span></summary><div className="px-4 pb-4 grid lg:grid-cols-3 gap-4 border-t border-slate-800 pt-4"><div><div className="text-[9px] font-black text-slate-500 uppercase">Target khóa</div><div className="text-xs text-slate-400 mt-2">7 mốc được tạo khi bắt đầu. App không nâng target chỉ vì bạn đang thắng.</div><div className="flex flex-wrap gap-1 mt-3">{state.lockedTargets.map((x,i)=><span key={i} className={`px-2 py-1 rounded-lg border text-[9px] ${i===currentRound-1?'border-amber-400/40 text-amber-300':'border-slate-800 text-slate-600'}`}>R{i+1} {x.toFixed(2)}</span>)}</div></div><div><div className="text-[9px] font-black text-slate-500 uppercase">Rival memory</div><div className="mt-2 space-y-2">{state.psychology.memories.slice(-4).reverse().map(m=><div key={m.id} className="text-[10px] text-slate-500 border-l-2 border-slate-800 pl-2"><b className="text-slate-400">{m.kind}</b> · {m.text}</div>)}{!state.psychology.memories.length&&<div className="text-[10px] text-slate-700">Chưa có callback đủ mạnh.</div>}</div></div><div><div className="text-[9px] font-black text-slate-500 uppercase">Ẩn sau lời nói</div><div className="mt-2 grid grid-cols-2 gap-2 text-[10px]">{[['Nể',state.psychology.respect],['Nóng trận',state.psychology.competitiveHeat],['Cay',state.psychology.irritation],['Nể ngầm',state.psychology.reluctantAdmiration]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-slate-900 p-2"><div className="text-slate-600">{k}</div><div className="text-white font-black mt-1">{Math.round(Number(v)*100)}%</div></div>)}</div><div className="text-[10px] text-slate-600 italic mt-3">“{state.psychology.lastBeat}”</div></div></div></details>
    </div>

    {final&&<div className="m-5 md:m-7 rounded-3xl border border-amber-400/40 bg-gradient-to-r from-amber-400/15 via-rose-500/10 to-slate-950 p-7 text-center"><Trophy className="mx-auto text-amber-300" size={30}/><div className="text-[10px] tracking-[.3em] font-black text-amber-300 mt-3">SERIES COMPLETE</div><div className="text-4xl font-black text-white mt-2">{userWins>legendWins?'YOU WIN':'RIVAL WINS'}</div><div className="text-lg font-black text-slate-300 mt-2">{userWins} — {legendWins}</div><div className="text-xs text-slate-500 mt-3">{userWins>legendWins?'Đối thủ đã phải công nhận. Trận này đã được ghi vào rivalry memory.':'Phục thù vẫn mở. Lần sau đối thủ vẫn nhớ trận này.'}</div></div>}
  </div>;
};

// V21.6 keeps both export contracts because existing App.tsx uses the named export.
export { LegendaryRivalry };
export default LegendaryRivalry;
