export interface Artwork { id:string; title:string; artist:string; query:string; value:string; valueNote:string; source:string; verified:string; accent:string; }
export interface FactCard { id:string; cat:string; text:string; }

export const ARTWORKS:Artwork[]=[
 ['starry-night','The Starry Night','Vincent van Gogh','The Starry Night Vincent van Gogh','Không có giá thị trường xác định','Tác phẩm thuộc MoMA, không phải món đang rao bán.','https://www.moma.org/collection/works/79802','rgba(38,91,160,.28)'],
 ['girl-pearl','Girl with a Pearl Earring','Johannes Vermeer','Girl with a Pearl Earring Vermeer','Không có giá thị trường xác định','Tác phẩm thuộc Mauritshuis.','https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring/','rgba(190,145,48,.22)'],
 ['mona-lisa','Mona Lisa','Leonardo da Vinci','Mona Lisa Leonardo da Vinci','Không có giá thị trường xác định','Tác phẩm thuộc Louvre; app không gán các con số ước đoán trên mạng thành giá bán.','https://collections.louvre.fr/en/ark:/53355/cl010062370','rgba(104,111,73,.25)'],
 ['scream','The Scream','Edvard Munch','The Scream Edvard Munch 1893','US$119,922,500 · mốc đấu giá bản pastel 1895 (2012)','Đây là mốc của một phiên bản khác trong loạt The Scream, không phải giá hiện tại của ảnh đang xem.','https://www.sothebys.com/en/articles/can-you-guess-sothebys-top-lot-of-every-year-since-2000','rgba(219,82,40,.22)'],
 ['american-gothic','American Gothic','Grant Wood','American Gothic Grant Wood','Không có giá thị trường xác định','Tác phẩm thuộc Art Institute of Chicago.','https://www.artic.edu/artworks/6565/american-gothic','rgba(112,84,51,.23)'],
 ['great-wave','The Great Wave off Kanagawa','Katsushika Hokusai','Great Wave off Kanagawa Hokusai','Không có một giá duy nhất','Có nhiều bản in lịch sử; giá phụ thuộc ấn bản và tình trạng.','https://www.metmuseum.org/art/collection/search/45434','rgba(30,93,137,.28)'],
 ['water-lilies','Water Lilies','Claude Monet','Water Lilies Claude Monet','Không có giá thị trường xác định cho tác phẩm bảo tàng này','Monet có nhiều tác phẩm cùng chủ đề; không lấy giá của bức khác gán vào.','https://www.metmuseum.org/art/collection/search/437127','rgba(38,111,92,.24)'],
 ['birth-venus','The Birth of Venus','Sandro Botticelli','Birth of Venus Botticelli','Không có giá thị trường xác định','Tác phẩm thuộc Uffizi.','https://www.uffizi.it/en/artworks/birth-of-venus','rgba(201,153,105,.22)'],
 ['kiss-klimt','The Kiss','Gustav Klimt','The Kiss Gustav Klimt','Không có giá thị trường xác định','Tác phẩm thuộc Belvedere Vienna.','https://www.belvedere.at/en/kiss-gustav-klimt','rgba(190,150,35,.25)'],
 ['persistence-memory','The Persistence of Memory','Salvador Dalí','Persistence of Memory Salvador Dali','Không có giá thị trường xác định','Tác phẩm thuộc MoMA.','https://www.moma.org/collection/works/79018','rgba(125,92,55,.22)'],
 ['night-watch','The Night Watch','Rembrandt','Night Watch Rembrandt','Không có giá thị trường xác định','Tác phẩm thuộc Rijksmuseum.','https://www.rijksmuseum.nl/en/collection/SK-C-5','rgba(104,74,42,.25)'],
 ['las-meninas','Las Meninas','Diego Velázquez','Las Meninas Velazquez','Không có giá thị trường xác định','Tác phẩm thuộc Museo del Prado.','https://www.museodelprado.es/en/the-collection/art-work/las-meninas','rgba(74,62,51,.25)'],
 ['creation-adam','The Creation of Adam','Michelangelo','Creation of Adam Michelangelo','Không có giá thị trường xác định','Là một phần trần Nhà nguyện Sistine, không phải món giao dịch.','https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/cappella-sistina.html','rgba(154,122,101,.22)'],
 ['school-athens','The School of Athens','Raphael','School of Athens Raphael','Không có giá thị trường xác định','Bích họa tại Vatican.','https://www.museivaticani.va/','rgba(148,110,74,.22)'],
 ['liberty-leading','Liberty Leading the People','Eugène Delacroix','Liberty Leading the People Delacroix','Không có giá thị trường xác định','Tác phẩm thuộc Louvre.','https://collections.louvre.fr/','rgba(101,67,43,.25)'],
 ['wanderer','Wanderer above the Sea of Fog','Caspar David Friedrich','Wanderer above the Sea of Fog Friedrich','Không có giá thị trường xác định','Tác phẩm thuộc Hamburger Kunsthalle.','https://www.hamburger-kunsthalle.de/','rgba(77,97,104,.26)'],
 ['arnolfini','The Arnolfini Portrait','Jan van Eyck','Arnolfini Portrait Jan van Eyck','Không có giá thị trường xác định','Tác phẩm thuộc National Gallery London.','https://www.nationalgallery.org.uk/paintings/jan-van-eyck-the-arnolfini-portrait','rgba(82,91,54,.24)'],
 ['garden-delights','The Garden of Earthly Delights','Hieronymus Bosch','Garden of Earthly Delights Bosch','Không có giá thị trường xác định','Tác phẩm thuộc Museo del Prado.','https://www.museodelprado.es/','rgba(80,112,77,.24)'],
 ['whistlers-mother','Whistler’s Mother','James McNeill Whistler','Whistlers Mother Whistler','Không có giá thị trường xác định','Tác phẩm thuộc Musée d’Orsay.','https://www.musee-orsay.fr/','rgba(86,78,72,.22)'],
 ['olympia','Olympia','Édouard Manet','Olympia Edouard Manet','Không có giá thị trường xác định','Tác phẩm thuộc Musée d’Orsay.','https://www.musee-orsay.fr/','rgba(127,99,81,.20)'],
 ['luncheon-grass','Le Déjeuner sur l’herbe','Édouard Manet','Dejeuner sur l herbe Manet','Không có giá thị trường xác định','Tác phẩm thuộc Musée d’Orsay.','https://www.musee-orsay.fr/','rgba(75,102,65,.23)'],
 ['bal-moulin','Bal du moulin de la Galette','Pierre-Auguste Renoir','Bal du moulin de la Galette Renoir','Không có giá thị trường xác định','Tác phẩm thuộc Musée d’Orsay.','https://www.musee-orsay.fr/','rgba(93,76,104,.23)'],
 ['impression-sunrise','Impression, Sunrise','Claude Monet','Impression Sunrise Monet','Không có giá thị trường xác định','Tác phẩm thuộc Musée Marmottan Monet.','https://www.marmottan.fr/','rgba(87,112,128,.24)'],
 ['bedroom-arles','The Bedroom','Vincent van Gogh','Bedroom in Arles Van Gogh','Không có giá thị trường xác định','Có nhiều phiên bản; app không lấy giá của bản khác.','https://www.vangoghmuseum.nl/','rgba(69,112,154,.24)'],
 ['cafe-terrace','Café Terrace at Night','Vincent van Gogh','Cafe Terrace at Night Van Gogh','Không có giá thị trường xác định','Tác phẩm thuộc Kröller-Müller Museum.','https://krollermuller.nl/en','rgba(34,79,131,.26)'],
 ['sunflowers','Sunflowers','Vincent van Gogh','Sunflowers Van Gogh London','Không có giá thị trường xác định','Có nhiều phiên bản; bản National Gallery không phải món đang giao dịch.','https://www.nationalgallery.org.uk/paintings/vincent-van-gogh-sunflowers','rgba(189,142,33,.24)'],
 ['irises','Irises','Vincent van Gogh','Irises Van Gogh Getty','Không có giá thị trường hiện hành','Tác phẩm thuộc Getty; giá mua lịch sử không phải giá bán hiện tại.','https://www.getty.edu/art/collection/','rgba(80,77,146,.25)'],
 ['red-vineyard','The Red Vineyard','Vincent van Gogh','Red Vineyard Van Gogh','Không có giá thị trường xác định','Tác phẩm thuộc Pushkin Museum.','https://pushkinmuseum.art/','rgba(153,61,40,.24)'],
 ['apple-orange','Apples and Oranges','Paul Cézanne','Apples and Oranges Cezanne','Không có giá thị trường xác định','Tác phẩm thuộc Musée d’Orsay.','https://www.musee-orsay.fr/','rgba(138,89,47,.23)'],
 ['card-players','The Card Players','Paul Cézanne','The Card Players Cezanne Musee Orsay','Không có giá thị trường xác định cho bản bảo tàng này','Có nhiều phiên bản; tránh gán giá bán của phiên bản khác.','https://www.musee-orsay.fr/','rgba(88,74,57,.23)'],
 ['dance-class','The Dance Class','Edgar Degas','Dance Class Edgar Degas','Không có giá thị trường xác định','Tác phẩm bảo tàng.','https://www.metmuseum.org/','rgba(120,99,72,.20)'],
 ['absinthe','L’Absinthe','Edgar Degas','Absinthe Edgar Degas','Không có giá thị trường xác định','Tác phẩm thuộc Musée d’Orsay.','https://www.musee-orsay.fr/','rgba(86,91,67,.22)'],
 ['thinker','The Thinker','Auguste Rodin','The Thinker Rodin','Không có một giá duy nhất','Có nhiều bản đúc hợp pháp; giá phụ thuộc phiên bản.','https://www.musee-rodin.fr/','rgba(84,72,63,.22)'],
 ['napoleon-alps','Napoleon Crossing the Alps','Jacques-Louis David','Napoleon Crossing Alps David','Không có giá thị trường xác định','Có nhiều phiên bản bảo tàng.','https://collections.chateauversailles.fr/','rgba(104,77,62,.23)'],
 ['death-marat','The Death of Marat','Jacques-Louis David','Death of Marat Jacques Louis David','Không có giá thị trường xác định','Tác phẩm thuộc Royal Museums of Fine Arts of Belgium.','https://fine-arts-museum.be/','rgba(68,61,57,.24)'],
 ['raft-medusa','The Raft of the Medusa','Théodore Géricault','Raft of the Medusa Gericault','Không có giá thị trường xác định','Tác phẩm thuộc Louvre.','https://collections.louvre.fr/','rgba(73,66,55,.24)'],
 ['fighting-temeraire','The Fighting Temeraire','J. M. W. Turner','Fighting Temeraire Turner','Không có giá thị trường xác định','Tác phẩm thuộc National Gallery London.','https://www.nationalgallery.org.uk/','rgba(112,93,79,.22)'],
 ['rain-steam-speed','Rain, Steam and Speed','J. M. W. Turner','Rain Steam and Speed Turner','Không có giá thị trường xác định','Tác phẩm thuộc National Gallery London.','https://www.nationalgallery.org.uk/','rgba(99,83,70,.22)'],
 ['hay-wain','The Hay Wain','John Constable','Hay Wain Constable','Không có giá thị trường xác định','Tác phẩm thuộc National Gallery London.','https://www.nationalgallery.org.uk/','rgba(68,92,68,.22)'],
 ['ophelia','Ophelia','John Everett Millais','Ophelia Millais','Không có giá thị trường xác định','Tác phẩm thuộc Tate.','https://www.tate.org.uk/art/artworks/millais-ophelia-n01543','rgba(45,101,73,.24)'],
 ['lady-shalott','The Lady of Shalott','John William Waterhouse','Lady of Shalott Waterhouse','Không có giá thị trường xác định','Tác phẩm thuộc Tate.','https://www.tate.org.uk/','rgba(91,80,58,.23)'],
 ['nighthawks','Nighthawks','Edward Hopper','Nighthawks Edward Hopper','Không có giá thị trường xác định','Tác phẩm thuộc Art Institute of Chicago.','https://www.artic.edu/artworks/111628/nighthawks','rgba(23,68,76,.28)'],
 ['christinas-world','Christina’s World','Andrew Wyeth','Christinas World Andrew Wyeth','Không có giá thị trường xác định','Tác phẩm thuộc MoMA.','https://www.moma.org/collection/works/78455','rgba(101,94,63,.23)'],
 ['meules','Meules (Haystacks)','Claude Monet','Meules Monet 1890','US$110,747,000 · Sotheby’s 2019','Mốc đấu giá lịch sử của tác phẩm Meules năm 2019.','https://www.sothebys.com/en/articles/monets-meules-sells-for-110-7-million','rgba(146,101,51,.22)'],
 ['lady-fan','Lady with a Fan','Gustav Klimt','Lady with a Fan Klimt','£85,305,800 · Sotheby’s 2023','Mốc đấu giá năm 2023.','https://www.sothebys.com/','rgba(170,125,43,.24)'],
 ['nu-couche','Nu couché','Amedeo Modigliani','Nu couche Modigliani 1917','US$170,405,000 · Christie’s 2015','Mốc đấu giá năm 2015.','https://www.christies.com/','rgba(147,94,75,.22)'],
 ['salvator-mundi','Salvator Mundi','Attributed to Leonardo da Vinci','Salvator Mundi Leonardo da Vinci','US$450,312,500 · Christie’s 2017','Mốc đấu giá 2017; attribution của tác phẩm vẫn là chủ đề tranh luận học thuật.','https://www.christies.com/','rgba(50,66,61,.26)'],
 ['milkmaid','The Milkmaid','Johannes Vermeer','The Milkmaid Vermeer','Không có giá thị trường xác định','Tác phẩm thuộc Rijksmuseum.','https://www.rijksmuseum.nl/en/collection/SK-A-2344','rgba(106,87,52,.22)'],
 ['windmill-wijk','The Windmill at Wijk bij Duurstede','Jacob van Ruisdael','Windmill at Wijk bij Duurstede Ruisdael','Không có giá thị trường xác định','Tác phẩm thuộc Rijksmuseum.','https://www.rijksmuseum.nl/','rgba(77,91,85,.22)'],
 ['hunters-snow','The Hunters in the Snow','Pieter Bruegel the Elder','Hunters in the Snow Bruegel','Không có giá thị trường xác định','Tác phẩm thuộc Kunsthistorisches Museum Vienna.','https://www.khm.at/','rgba(90,107,104,.24)'],
].map((x:any)=>({id:x[0],title:x[1],artist:x[2],query:x[3],value:x[4],valueNote:x[5],source:x[6],verified:'2026-08-08',accent:x[7]}));


export const FACTS:FactCard[]=[
 ['psy-1','Tâm lý','Não thường dễ bắt đầu một việc nhỏ hơn một việc nghe quá lớn. Vì vậy “làm 2 phút” có thể hữu ích hơn “phải làm xong”.'],
 ['psy-2','Tâm lý','Ký ức không giống video. Mỗi lần nhớ lại, não có thể ghép lại một phần câu chuyện.'],
 ['psy-3','Tâm lý','Ta thường đánh giá một việc khó hơn khi đang mệt. Cùng một việc, sáng và tối có thể cho cảm giác rất khác.'],
 ['psy-4','Tâm lý','Một phần lý do danh sách việc dài gây nặng đầu là vì những việc chưa xong dễ quay lại trong suy nghĩ.'],
 ['science-1','Khoa học','Không khí quanh một tia chớp có thể nóng hơn bề mặt Mặt Trời trong chốc lát.'],
 ['science-2','Khoa học','Nước nở ra khi đóng băng. Vì vậy băng nổi trên nước thay vì chìm.'],
 ['science-3','Khoa học','Âm thanh truyền trong nước nhanh hơn trong không khí.'],
 ['science-4','Khoa học','Một ngày trên sao Kim dài hơn một năm trên chính sao Kim.'],
 ['animal-1','Động vật','Bạch tuộc có ba trái tim.'],
 ['animal-2','Động vật','Quạ có thể nhớ khuôn mặt người và học từ những con quạ khác.'],
 ['animal-3','Động vật','Rái cá biển đôi khi nắm tay nhau khi ngủ để khỏi trôi xa.'],
 ['animal-4','Động vật','Một số loài chim có thể ngủ bằng một nửa bộ não trong khi nửa còn lại vẫn tỉnh.'],
 ['animal-5','Động vật','Cá heo có những tiếng gọi riêng giống như “tên” để nhận ra nhau.'],
 ['space-1','Vũ trụ','Ánh sáng từ Mặt Trời mất khoảng 8 phút 20 giây để tới Trái Đất.'],
 ['space-2','Vũ trụ','Trên Mặt Trăng, dấu chân có thể tồn tại rất lâu vì gần như không có gió hay mưa để xóa.'],
 ['space-3','Vũ trụ','Sao neutron có mật độ vật chất lớn đến mức một lượng rất nhỏ cũng có khối lượng khổng lồ.'],
 ['brain-1','Não bộ','Não chỉ chiếm một phần nhỏ khối lượng cơ thể nhưng dùng rất nhiều năng lượng ngay cả khi ta nghỉ.'],
 ['brain-2','Não bộ','Khi học một kỹ năng mới, giấc ngủ giúp não củng cố những gì vừa luyện.'],
 ['brain-3','Não bộ','Não không có thụ thể đau như da; đau đầu thường đến từ các cấu trúc quanh não.'],
 ['history-1','Lịch sử','Oxford đã có hoạt động giảng dạy trước khi đế chế Aztec được thành lập.'],
 ['history-2','Lịch sử','Cleopatra sống gần thời điểm con người đặt chân lên Mặt Trăng hơn là thời điểm Kim tự tháp Giza được xây.'],
 ['history-3','Lịch sử','Nhiều màu tím từng cực đắt vì phải tạo từ một lượng rất lớn ốc biển.'],
 ['art-1','Nghệ thuật','Van Gogh vẽ The Starry Night ở Saint-Rémy, nhưng bầu trời trong tranh không phải bản sao chính xác của cảnh ông nhìn thấy.'],
 ['art-2','Nghệ thuật','The Great Wave là một bản in mộc bản, nên tồn tại nhiều bản in chứ không chỉ một “bản gốc” duy nhất như tranh sơn dầu.'],
 ['art-3','Nghệ thuật','Mona Lisa nổi tiếng với kỹ thuật chuyển sắc rất mềm, khiến đường nét quanh khuôn mặt khó thấy rõ.'],
 ['art-4','Nghệ thuật','Nhiều tác phẩm trong bảo tàng không có “giá thị trường hiện tại” vì chúng không phải món đang được bán.'],
 ['tech-1','Công nghệ','Từ “bug” đã có trước máy tính. Con bướm đêm mắc trong Harvard Mark II chỉ làm câu chuyện về “bug máy tính” nổi tiếng hơn.'],
 ['tech-2','Công nghệ','Email xuất hiện trước World Wide Web.'],
 ['tech-3','Công nghệ','Mã QR được phát minh để theo dõi linh kiện trong sản xuất ô tô.'],
 ['body-1','Cơ thể','Da là cơ quan lớn nhất của cơ thể người.'],
 ['body-2','Cơ thể','Xương là mô sống: nó liên tục được phá đi và xây lại.'],
 ['body-3','Cơ thể','Giác mạc không có mạch máu; nó nhận oxy trực tiếp từ không khí và nước mắt.'],
 ['nature-1','Thiên nhiên','Rễ cây và nấm trong đất có thể trao đổi chất và tín hiệu trong những mạng lưới rất phức tạp.'],
 ['nature-2','Thiên nhiên','Tre là cỏ, không phải cây gỗ theo cách phân loại thực vật.'],
 ['nature-3','Thiên nhiên','Một số hạt giống có thể ngủ rất lâu rồi nảy mầm khi điều kiện phù hợp.'],
 ['language-1','Ngôn ngữ','Ngôn ngữ luôn thay đổi. Nhiều từ từng bị xem là “sai” sau này lại trở thành cách dùng bình thường.'],
 ['language-2','Ngôn ngữ','Trẻ nhỏ thường hiểu nhiều từ hơn số từ chúng có thể tự nói.'],
 ['philo-1','Triết học','“Nghịch lý con tàu Theseus” hỏi: nếu thay từng bộ phận của một vật, đến lúc nào nó không còn là vật cũ?'],
 ['math-1','Toán học','Số 0 không phải lúc nào cũng được các nền văn minh cổ dùng như một con số độc lập.'],
 ['math-2','Toán học','Có vô hạn số nguyên tố. Euclid đã có một chứng minh nổi tiếng cho điều này từ thời cổ đại.'],
].map((x:any)=>({id:x[0],cat:x[1],text:x[2]}));

